package com.emojifloat.app;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.ColorDrawable;import android.os.*;import android.provider.Settings;import android.view.*;import android.view.animation.*;import android.widget.*;import org.json.*;import java.io.ByteArrayInputStream;import java.io.File;import java.io.FileOutputStream;import android.net.Uri;import java.util.*;
public class FloatingEmojiService extends Service {
 public static final String ACTION_UPDATE="com.emojifloat.app.UPDATE"; private WindowManager wm; private FrameLayout root; private final List<View> views=new ArrayList<>();
 @Override public void onCreate(){super.onCreate();wm=(WindowManager)getSystemService(WINDOW_SERVICE);createChannel();startForeground(77,buildNotification());}
 @Override public int onStartCommand(Intent intent,int flags,int startId){if(intent!=null&&intent.hasExtra("overlays"))render(intent.getStringExtra("overlays"));return START_STICKY;}
 private Notification buildNotification(){Intent launch=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,launch,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,"floating").setContentTitle("EmojiFloat is active").setContentText("Floating emojis and stickers are running").setSmallIcon(android.R.drawable.ic_dialog_info).setContentIntent(pi).setOngoing(true).build();}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("floating","Floating Emoji",NotificationManager.IMPORTANCE_LOW);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c);}}
 private void ensureRoot(){if(root!=null)return;root=new FrameLayout(this);root.setBackground(new ColorDrawable(Color.TRANSPARENT));WindowManager.LayoutParams p=new WindowManager.LayoutParams(WindowManager.LayoutParams.MATCH_PARENT,WindowManager.LayoutParams.MATCH_PARENT,Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,PixelFormat.TRANSLUCENT);p.gravity=Gravity.TOP|Gravity.START;wm.addView(root,p);}
 private void render(String payload){if(!Settings.canDrawOverlays(this))return;ensureRoot();root.removeAllViews();views.clear();try{JSONArray arr=new JSONArray(payload==null?"[]":payload);for(int i=0;i<arr.length();i++)addOverlay(arr.getJSONObject(i));}catch(Exception ignored){}}
 private void addOverlay(JSONObject o)throws Exception{String type=o.optString("type","preset"),src=o.optString("src","✨");int size=Math.max(24,o.optInt("size",56));float opacity=(float)Math.max(0,Math.min(1,o.optDouble("opacity",1)));float rotation=(float)o.optDouble("rotation",0);float xPct=(float)o.optDouble("x",50)/100f,yPct=(float)o.optDouble("y",50)/100f;View v;if(type.equals("custom_image")&&src.startsWith("data:")){ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.FIT_CENTER);image.setImageBitmap(decodeDataUrl(src));v=image;}else if(type.equals("custom_video")&&src.startsWith("data:")){VideoView video=new VideoView(this);video.setVideoURI(Uri.parse(writeDataUrlToFile(src)));video.setOnPreparedListener(mp->{mp.setLooping(true);mp.setVolume(0f,0f);});video.start();v=video;}else{TextView tv=new TextView(this);tv.setText(src);tv.setTextSize(size*.55f);tv.setGravity(Gravity.CENTER);tv.setIncludeFontPadding(false);v=tv;}v.setAlpha(opacity);v.setRotation(rotation);FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(size,size);root.post(()->{int w=root.getWidth(),h=root.getHeight();lp.leftMargin=Math.max(0,(int)(w*xPct)-size/2);lp.topMargin=Math.max(0,(int)(h*yPct)-size/2);root.addView(v,lp);attachDrag(v,lp);animate(v,o.optString("animation","none"));});views.add(v);}
 private Bitmap decodeDataUrl(String data){try{String b64=data.substring(data.indexOf(',')+1);byte[] bytes=android.util.Base64.decode(b64,android.util.Base64.DEFAULT);return BitmapFactory.decodeStream(new ByteArrayInputStream(bytes));}catch(Exception e){return null;}}
 private String writeDataUrlToFile(String data){try{String meta=data.substring(0,data.indexOf(','));String b64=data.substring(data.indexOf(',')+1);String ext=meta.contains("video/webm")?"webm":meta.contains("video/quicktime")?"mov":"mp4";File f=new File(getCacheDir(),"sticker."+ext);FileOutputStream out=new FileOutputStream(f);out.write(android.util.Base64.decode(b64,android.util.Base64.DEFAULT));out.close();return Uri.fromFile(f).toString();}catch(Exception e){return "";}}
 private void attachDrag(View v,FrameLayout.LayoutParams lp){v.setOnTouchListener((view,e)->{switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:view.setTag(new float[]{e.getRawX(),e.getRawY(),lp.leftMargin,lp.topMargin});return true;case MotionEvent.ACTION_MOVE:float[] t=(float[])view.getTag();lp.leftMargin=(int)(t[2]+e.getRawX()-t[0]);lp.topMargin=(int)(t[3]+e.getRawY()-t[1]);view.setLayoutParams(lp);return true;default:return true;}});}
 private void animate(View v,String mode){if("float".equals(mode)){TranslateAnimation a=new TranslateAnimation(0,0,0,-14);a.setDuration(900);a.setRepeatMode(Animation.REVERSE);a.setRepeatCount(Animation.INFINITE);v.startAnimation(a);}else if("bounce".equals(mode)){TranslateAnimation a=new TranslateAnimation(0,0,0,-22);a.setDuration(450);a.setRepeatMode(Animation.REVERSE);a.setRepeatCount(Animation.INFINITE);v.startAnimation(a);}else if("pulse".equals(mode)){ScaleAnimation a=new ScaleAnimation(1,1.12f,1,1.12f,Animation.RELATIVE_TO_SELF,.5f,Animation.RELATIVE_TO_SELF,.5f);a.setDuration(650);a.setRepeatMode(Animation.REVERSE);a.setRepeatCount(Animation.INFINITE);v.startAnimation(a);}else if("spin".equals(mode)){RotateAnimation a=new RotateAnimation(0,360,Animation.RELATIVE_TO_SELF,.5f,Animation.RELATIVE_TO_SELF,.5f);a.setDuration(1200);a.setRepeatCount(Animation.INFINITE);v.startAnimation(a);}}
 @Override public void onDestroy(){if(root!=null){try{wm.removeView(root);}catch(Exception ignored){}root=null;}super.onDestroy();}@Override public IBinder onBind(Intent intent){return null;}
}
